env:
  CF_APPNAME: buildkite-cloudfoundry-demo-app

steps:
  - label: ":cloudfoundry:"
    commands:
    -  ".buildkite/scripts/cf-login.sh"
    -  ".buildkite/scripts/cf-push-or-action.sh"
    concurrency: 1
    concurrency_group: "cf-push"
    # plugins:
    #   - docker#v3.5.0:
    #       image: "starkandwayne/update-all-cf-buildpacks:latest"
    #       propagate-environment: true
    timeout_in_minutes: 5
