env:
  CF_APPNAME: buildkite-cloudfoundry-demo-app

steps:
  # - plugins:
  #   # https://github.com/buildkite-plugins/detect-clowns-buildkite-plugin
  #   - detect-clowns#v2.0.0: ~

  # https://buildkite.com/docs/deployments#manual-approval-steps
  # - block: "Deploy"
  #   prompt: "Deploy to production?"

  - label: ":cloudfoundry: staging"
    commands:
    -  ".buildkite/scripts/cf-login.sh"
    -  ".buildkite/scripts/cf-push-or-action.sh"
    -  ".buildkite/scripts/cf-annotations.sh"
    concurrency: 1
    concurrency_group: "cf-push-staging"
    # plugins:
    #   - docker#v3.5.0:
    #       image: "starkandwayne/update-all-cf-buildpacks:latest"
    #       propagate-environment: true
    timeout_in_minutes: 5
    env:
      CF_SPACE_SELECTOR: CF_SPACE_STAGING
      CF_ROUTE_SELECTOR: CF_ROUTE_STAGING

  - block: "Deploy"
    prompt: "Deploy to production?"

  - label: ":cloudfoundry: production"
    commands:
    -  ".buildkite/scripts/cf-login.sh"
    -  ".buildkite/scripts/cf-push-or-action.sh"
    -  ".buildkite/scripts/cf-annotations.sh"
    concurrency: 1
    concurrency_group: "cf-push-production"
    # plugins:
    #   - docker#v3.5.0:
    #       image: "starkandwayne/update-all-cf-buildpacks:latest"
    #       propagate-environment: true
    timeout_in_minutes: 5
    env:
      CF_SPACE_SELECTOR: CF_SPACE_PRODUCTION
      CF_ROUTE_SELECTOR: CF_ROUTE_PRODUCTION
