steps:
  - label: ":docker:"
    command:
      - "docker build . -t starkandwayne/buildkite-cloudfoundry-demo-app:latest"
      - "docker push starkandwayne/buildkite-cloudfoundry-demo-app:latest"
    plugins:
      - docker-login#v2.0.1:
          username: drnic
          password-env: DOCKER_LOGIN_PASSWORD
