
steps:
  # - plugins:
  #   # https://github.com/buildkite-plugins/detect-clowns-buildkite-plugin
  #   - detect-clowns#v2.0.0: ~

  # https://buildkite.com/docs/deployments#manual-approval-steps
  # - block: "Deploy"
  #   prompt: "Deploy to production?"
  - block: "Deployment"
    prompt: "Fill out the details for deployment"
    fields:
      - text: "Organization"
        key: "cf-organization"
        hint: "`cf target -o <org>`"
      - text: "Space"
        key: "cf-space"
        hint: "`cf target -s <space>`"

  - label: ":cloudfoundry:"
    command: "ci/scripts/cf-push.sh"
    artifact_paths: "."
    concurrency: 1
    concurrency_group: "cf-push"
    plugins:
      - docker#v3.5.0:
          image: "starkandwayne/update-all-cf-buildpacks:latest"
          propagate-environment: true
    timeout_in_minutes: 5
    env:
      CF_API: ""
      CF_SKIP_SSL_VALIDATION: ""
      CF_USERNAME: ""
      CF_PASSWORD: ""
