name: "Cloud Foundry Demo App"
description: "An example repository to deploy an application to Cloud Foundry"
steps:
  - block: "Deployment"
    prompt: "Fill out the details for deployment"
    fields:
      - text: "Organization"
        key: "cf-organization"
        hint: "`cf target -o <org>`"
      - text: "Space"
        key: "cf-space"
        hint: "`cf target -s <space>`"
  - command: "buildkite-agent pipeline upload"
    label: ":pipeline:"
