name: "Cloud Foundry Demo App"
description: |
  Deploy an application to CF, with optional staging -> production.
env:
  CF_ORGANIZATION: ""
  CF_SPACE_STAGING: ""
  CF_ROUTE_STAGING: ""
  CF_SPACE_PRODUCTION: "<optional>"
  CF_ROUTE_PRODUCTION: "<optional>"
  CF_API: "<should provide via secrets>"
  CF_USERNAME: "<should provide via secrets>"
  CF_PASSWORD: "<should provide via secrets>"
  CF_SKIP_SSL_VALIDATION: "<optional>"

steps:
  - command: "buildkite-agent pipeline upload .buildkite/pipeline.dynamic.yml"
    label: ":pipeline:"
