name: "Cloud Foundry Demo App"
description: "An example repository to deploy an application to Cloud Foundry"
steps:
  - command: "buildkite-agent pipeline upload .buildkite/pipeline.single.yml"
    label: ":pipeline:"
